[tools]
biome = "latest"
bun = "latest"
claude-code = "latest"
codex = "latest"
deno = "latest"
fnox  = "latest"
gradle = "latest"
java = "latest"
node  = "25"
npm = "latest"
"npm:esbuild" = "0.25"
"npm:mjml" = "latest"
"npm:prettier-language-server" = "latest"
"npm:serve" = "latest"
"npm:update-ts-references" = "latest"
"npm:zx" = "latest"
"pipx:marker-pdf" = "latest"
pnpm = "latest"
prettier = "latest"
python = "latest"
rust = "nightly"
usage = "latest"
uv = "latest"
wrangler = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node", "java"]
