[tools]
# {{{ sandbox
biome                                 = "latest"
bun                                   = "latest"
codex                                 = "latest"
fnox                                  = "latest"
node                                  = "latest"
npm                                   = "latest"
"npm:@github/copilot"                 = "latest"
"npm:@google/gemini-cli"              = "latest"
"npm:@openai/codex"                   = "latest"
"npm:@zed-industries/claude-code-acp" = "latest"
"npm:esbuild"                         = "0.25"
"npm:prettier-language-server"        = "latest"
"npm:serve"                           = "latest"
"npm:update-ts-references"            = "latest"
"npm:zx"                              = "latest"
opencode                              = "latest"
pipx                                  = "latest"
pnpm                                  = "latest"
prettier                              = "latest"
python                                = "latest"
usage                                 = "latest"
wrangler                              = "latest"
# }}}

cargo-binstall          = "latest"
"cargo:cbor-cli"        = "latest"
"cargo:neovide"         = "latest"
"cargo:resvg"           = "latest"
"cargo:tree-sitter-cli" = "latest"
"cargo:worktrunk"       = "latest"
deno                    = "latest"
gradle                  = "latest"
java                    = "openjdk-21"
"npm:aedes-cli"         = "latest"
"npm:edge-impulse-cli"  = "latest"
"npm:mjml"              = "latest"
"npm:npkill"            = "latest"
"pipx:cbor2"            = "latest"
"pipx:fit-tool"         = "latest"
"pipx:marker-pdf"       = "latest"
rust                    = "latest"
uv                      = "latest"
"npm:jscpd" = "latest"
"npm:oxfmt" = "latest"
"npm:oxlint" = "latest"
"npm:@jimsheen/yalc" = "latest"

[settings]
experimental                        = true
idiomatic_version_file_enable_tools = ["java", "node"]
lockfile                            = true
