[tools]
biome = "latest"
bun = "latest"
claude-code = "latest"
codex = "latest"
fnox  = "latest"
node  = "25"
"npm:mjml" = "latest"
"npm:prettier-language-server" = "latest"
"npm:serve" = "latest"
"npm:zx" = "latest"
pnpm = "latest"
prettier = "latest"
usage = "latest"
wrangler = "latest"
