[tools]
biome                          = "latest"
bun                            = "latest"
"cargo:cbor-cli"               = "latest"
"cargo:tree-sitter-cli"        = "latest"
"cargo:worktrunk"              = "latest"
claude-code                    = "latest"
codex                          = "latest"
deno                           = "latest"
fnox                           = "1.6.0"
gradle                         = "latest"
java                           = "openjdk-21"
node                           = "25"
npm                            = "latest"
"npm:@google/gemini-cli"       = "latest"
"npm:@openai/codex"            = "latest"
"npm:edge-impulse-cli"         = "latest"
"npm:esbuild"                  = "0.25"
"npm:mjml"                     = "latest"
"npm:npkill" = "latest"
"npm:prettier-language-server" = "latest"
"npm:serve"                    = "latest"
"npm:update-ts-references"     = "latest"
"npm:zx"                       = "latest"
"pipx:cbor2" = "latest"
"pipx:fit-tool" = "latest"
"pipx:marker-pdf"              = "latest"
pnpm                           = "latest"
prettier                       = "latest"
python                         = "latest"
rust                           = "nightly"
usage                          = "latest"
uv                             = "latest"
wrangler                       = "latest"

[settings]
idiomatic_version_file_enable_tools = ["java", "node"]
